{% set name = "slowapi" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slowapi-{{ version }}.tar.gz
  sha256: d320d5bc04d9f171a77fb16700faf3036d85b00f420f22924c8a225f95bd14f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - limits >=2.3
    - starlette
  run_constrained:
    - redis-py >=3.4.1,<4.0.0

test:
  imports:
    - slowapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/laurents/slowapi
  summary: A rate limiting extension for Starlette and Fastapi
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
